export const FETCH_LOGIN = 'FETCH_LOGIN'

export const FETCH_GET_CHAT_LIST = 'FETCH_GET_CHAT_LIST'
export const FETCH_GET_FOLLOWING = 'FETCH_GET_FOLLOWING'
export const FETCH_GET_HOME_TIMELINE = 'FETCH_GET_HOME_TIMELINE'
export const FETCH_GET_HAS_NEW_RECS = 'FETCH_GET_HAS_NEW_RECS'
export const FETCH_GET_CHAT_MESSAGES = 'FETCH_GET_CHAT_MESSAGES'

export const SET_USER_INFO = 'SET_USER_INFO'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const GET_CHAT_LIST_SUCCESS = 'GET_CHAT_LIST_SUCCESS'
export const GET_CHAT_MESSAGES_SUCCESS = 'GET_CHAT_MESSAGES_SUCCESS'

export const SET_ACTIVE_CHAT_ID = 'SET_ACTIVE_CHAT_ID'
