// actions

export const FETCH_POST_LOGIN = 'FETCH_POST_LOGIN'

export const FETCH_GET_CHAT_LIST = 'FETCH_GET_CHAT_LIST'
export const FETCH_GET_CHAT_LIST_MORE = 'FETCH_GET_CHAT_LIST_MORE'
// export const FETCH_GET_FOLLOWING = 'FETCH_GET_FOLLOWING'
// export const FETCH_GET_HOME_TIMELINE = 'FETCH_GET_HOME_TIMELINE'
// export const FETCH_GET_HAS_NEW_RECS = 'FETCH_GET_HAS_NEW_RECS'
export const FETCH_GET_CHAT_MESSAGES = 'FETCH_GET_CHAT_MESSAGES'
export const FETCH_GET_CHAT_MESSAGES_IF_NEEDED = 'FETCH_GET_CHAT_MESSAGES_IF_NEEDED'
export const FETCH_GET_CHAT_MESSAGES_MORE = 'FETCH_GET_CHAT_MESSAGES_MORE'
export const FETCH_POST_CHAT_MESSAGE = 'FETCH_POST_CHAT_MESSAGE'
export const FETCH_SYNC_CHAT_MESSAGE = 'FETCH_SYNC_CHAT_MESSAGE'
export const FETCH_READ_CHAT_MESSAGE = 'FETCH_READ_CHAT_MESSAGE'

export const INIT_USRE_INFO_FROM_STORAGE = 'INIT_USRE_INFO_FROM_STORAGE'

export const CHANGE_ACTIVE_CHAT_ID = 'CHANGE_ACTIVE_CHAT_ID'

// mutations

export const SET_USER_INFO = 'SET_USER_INFO'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const GET_CHAT_LIST_REQUEST = 'GET_CHAT_LIST_REQUEST'
export const GET_CHAT_LIST_FAILURE = 'GET_CHAT_LIST_FAILURE'
export const GET_CHAT_LIST_SUCCESS = 'GET_CHAT_LIST_SUCCESS'
export const GET_CHAT_LIST_MORE_REQUEST = 'GET_CHAT_LIST_MORE_REQUEST'
export const GET_CHAT_LIST_MORE_FAILURE = 'GET_CHAT_LIST_MORE_FAILURE'
export const GET_CHAT_LIST_MORE_SUCCESS = 'GET_CHAT_LIST_MORE_SUCCESS'
export const GET_CHAT_MESSAGES_REQUEST = 'GET_CHAT_MESSAGES_REQUEST'
export const GET_CHAT_MESSAGES_SUCCESS = 'GET_CHAT_MESSAGES_SUCCESS'
export const GET_CHAT_MESSAGES_MORE_REQUEST = 'GET_CHAT_MESSAGES_MORE_REQUEST'
export const GET_CHAT_MESSAGES_MORE_SUCCESS = 'GET_CHAT_MESSAGES_MORE_SUCCESS'
export const POST_CHAT_MESSAGE_REQUEST = 'POST_CHAT_MESSAGE_REQUEST'
export const POST_CHAT_MESSAGE_FAILURE = 'POST_CHAT_MESSAGE_FAILURE'
export const POST_CHAT_MESSAGE_SUCCESS = 'POST_CHAT_MESSAGE_SUCCESS'
export const SYNC_CHAT_MESSAGE_SUCCESS = 'SYNC_CHAT_MESSAGE_SUCCESS'
export const LOAD_CHAT_MESSAGES = 'LOAD_CHAT_MESSAGES'
export const LOAD_CHAT_MESSAGES_MORE = 'LOAD_CHAT_MESSAGES_MORE'
export const CACHE_CHAT_MESSAGE = 'CACHE_CHAT_MESSAGE'
export const READ_CHAT_MESSAGE_SUCCESS = 'READ_CHAT_MESSAGE_SUCCESS'
export const READ_CHAT_MESSAGE_FAILURE = 'READ_CHAT_MESSAGE_FAILURE'
export const READ_CHAT_MESSAGE_REQUEST = 'READ_CHAT_MESSAGE_REQUEST'

export const SET_ACTIVE_CHAT_ID = 'SET_ACTIVE_CHAT_ID'
export const SET_DISACTIVE_CHAT_ID = 'SET_DISACTIVE_CHAT_ID'
